import type { MailyLabels, MailyMailboxLabels } from "@/components/maily"

/**
 * A complete Polish translation of the Maily editor.
 *
 * `MailyLabels` is `Record<LabelKey, string>` — a COMPLETE language, not a
 * partial. If you delete any line below, TypeScript fails to compile and names
 * the missing key. That is the i18n contract working as designed.
 */
export const polishLabels: MailyLabels = {
  // ── Slash-command default blocks ──
  "block.text.title": "Tekst",
  "block.text.description": "Po prostu zacznij pisać zwykły tekst.",
  "block.heading1.title": "Nagłówek 1",
  "block.heading1.description": "Duży nagłówek.",
  "block.heading2.title": "Nagłówek 2",
  "block.heading2.description": "Średni nagłówek.",
  "block.heading3.title": "Nagłówek 3",
  "block.heading3.description": "Mały nagłówek.",
  "block.bulletList.title": "Lista punktowana",
  "block.bulletList.description": "Utwórz prostą listę punktowaną.",
  "block.orderedList.title": "Lista numerowana",
  "block.orderedList.description": "Utwórz listę z numeracją.",
  "block.image.title": "Obraz",
  "block.image.description": "Obraz na całą szerokość",
  "block.logo.title": "Logo",
  "block.logo.description": "Dodaj logo swojej marki",
  "block.inlineImage.title": "Obraz w tekście",
  "block.inlineImage.description": "Obraz w linii tekstu",
  "block.columns.title": "Kolumny",
  "block.columns.description": "Dodaj kolumny do wiadomości.",
  "block.section.title": "Sekcja",
  "block.section.description": "Dodaj sekcję do wiadomości.",
  "block.repeat.title": "Powtórzenie",
  "block.repeat.description": "Iteruj po tablicy elementów.",
  "block.divider.title": "Separator",
  "block.divider.description": "Dodaj poziomy separator.",
  "block.spacer.title": "Odstęp",
  "block.spacer.description": "Dodaj odstęp między blokami.",
  "block.button.title": "Przycisk",
  "block.button.description": "Dodaj przycisk wezwania do działania.",
  "block.linkCard.title": "Karta linku",
  "block.linkCard.description": "Dodaj kartę linku do wiadomości.",
  "block.hardBreak.title": "Twardy podział",
  "block.hardBreak.description": "Dodaj podział między wierszami.",
  "block.blockquote.title": "Cytat",
  "block.blockquote.description": "Dodaj cytat blokowy.",
  "block.footer.title": "Stopka",
  "block.footer.description": "Dodaj tekst stopki do wiadomości.",
  "block.clearLine.title": "Wyczyść wiersz",
  "block.clearLine.description": "Wyczyść bieżący wiersz.",
  "block.htmlCodeBlock.title": "Własny HTML",
  "block.htmlCodeBlock.description": "Wstaw własny blok HTML",
  "block.headers.title": "Nagłówki",
  "block.headers.description": "Dodaj gotowy blok nagłówka",
  "block.footers.title": "Stopki",
  "block.footers.description": "Dodaj gotowy blok stopki",
  "block.headerLogoWithTextVertical.title": "Logo z tekstem (pionowo)",
  "block.headerLogoWithTextVertical.description": "Logo i tekst w pionie",
  "block.headerLogoWithTextHorizontal.title": "Logo z tekstem (poziomo)",
  "block.headerLogoWithTextHorizontal.description": "Logo i tekst w poziomie",
  "block.headerLogoWithCoverImage.title": "Logo z obrazem tła",
  "block.headerLogoWithCoverImage.description": "Logo i obraz tła",
  "block.footerCopyrightText.title": "Stopka — prawa autorskie",
  "block.footerCopyrightText.description": "Tekst praw autorskich w stopce.",
  "block.footerCommunityFeedbackCta.title": "Stopka — CTA opinii społeczności",
  "block.footerCommunityFeedbackCta.description":
    "Wezwanie do podzielenia się opinią w stopce.",
  "block.footerCompanySignature.title": "Stopka — podpis firmy",
  "block.footerCompanySignature.description": "Podpis firmy w stopce.",

  // ── Slash-command chrome ──
  "slashCommand.group.blocks": "Bloki",
  "slashCommand.group.components": "Komponenty",
  "slashCommand.navigate": "aby nawigować",
  "slashCommand.select": "aby wybrać",
  "slashCommand.enter": "Enter",

  // ── Placeholders ──
  "placeholder.default": "Zacznij pisać lub wpisz / aby zobaczyć polecenia",
  "placeholder.heading": "Nagłówek {level}",
  "placeholder.html": "Wpisz swój kod HTML...",

  // ── Text bubble menu ──
  "toolbar.bold": "Pogrubienie",
  "toolbar.italic": "Kursywa",
  "toolbar.underline": "Podkreślenie",
  "toolbar.strikethrough": "Przekreślenie",
  "toolbar.code": "Kod",
  "toolbar.bulletList": "Lista punktowana",
  "toolbar.orderedList": "Lista numerowana",
  "toolbar.link": "Zewnętrzny adres URL",
  "toolbar.linkPrompt": "Wprowadź adres URL",
  "toolbar.textColor": "Kolor tekstu",
  "toolbar.fontFamily": "Krój pisma",
  "toolbar.fontSize": "Rozmiar tekstu",
  "fontSize.default": "Domyślny",

  // ── Font family picker ──
  "fontPicker.search": "Szukaj fontów Fontsource...",
  "fontPicker.default": "Domyślny wiadomości",
  "fontPicker.defaultDescription": "Użyj fontu motywu wiadomości",
  "fontPicker.loading": "Ładowanie fontów",
  "fontPicker.loadError": "Nie udało się załadować fontów",
  "fontPicker.loadErrorDescription": "Sprawdź połączenie i spróbuj ponownie.",
  "fontPicker.retry": "Spróbuj ponownie",
  "fontPicker.noResults": "Nie znaleziono fontów.",
  "fontPicker.category.sansSerif": "Bezszeryfowy",
  "fontPicker.category.serif": "Szeryfowy",
  "fontPicker.category.display": "Dekoracyjny",
  "fontPicker.category.handwriting": "Odręczny",
  "fontPicker.category.monospace": "Stałej szerokości",

  // ── Turn-into menu ──
  "turnInto.label": "Zmień na",
  "turnInto.hierarchy": "Hierarchia",
  "turnInto.paragraph": "Akapit",
  "turnInto.heading1": "Nagłówek 1",
  "turnInto.heading2": "Nagłówek 2",
  "turnInto.heading3": "Nagłówek 3",
  "turnInto.footer": "Stopka",
  "turnInto.lists": "Listy",
  "turnInto.bulletList": "Lista punktowana",
  "turnInto.numberedList": "Lista numerowana",

  // ── Alignment / direction / vertical-alignment switches ──
  "alignment.left": "Wyrównaj do lewej",
  "alignment.center": "Wyśrodkuj",
  "alignment.right": "Wyrównaj do prawej",
  "alignment.label": "Wyrównanie",
  "direction.ltr": "Od lewej do prawej",
  "direction.rtl": "Od prawej do lewej",
  "direction.label": "Kierunek tekstu",
  "verticalAlignment.top": "Wyrównaj do góry",
  "verticalAlignment.center": "Wyśrodkuj w pionie",
  "verticalAlignment.bottom": "Wyrównaj do dołu",
  "verticalAlignment.label": "Wyrównanie w pionie",

  // ── Section bubble menu ──
  "sectionMenu.borderRadius": "Zaokrąglenie rogów",
  "sectionMenu.radius.sharp": "Ostre",
  "sectionMenu.radius.smooth": "Lekkie",
  "sectionMenu.radius.round": "Zaokrąglone",
  "sectionMenu.borderWidth": "Grubość obramowania",
  "sectionMenu.borderWidth.none": "Brak",
  "sectionMenu.borderWidth.thin": "Cienkie",
  "sectionMenu.borderWidth.medium": "Średnie",
  "sectionMenu.borderWidth.thick": "Grube",
  "sectionMenu.margin": "Margines",
  "sectionMenu.margin.none": "Brak",
  "sectionMenu.padding": "Wypełnienie",
  "sectionMenu.padding.none": "Brak",
  "sectionMenu.borderColor": "Kolor obramowania",
  "sectionMenu.backgroundColor": "Kolor tła",
  "sectionMenu.delete": "Usuń sekcję",
  "sectionMenu.column": "Kolumna",

  // ── Image / inline-image menus ──
  "imageMenu.size": "Rozmiar",
  "imageMenu.borderRadius": "Zaokrąglenie rogów",
  "imageMenu.radius.sharp": "Ostre",
  "imageMenu.radius.smooth": "Lekkie",
  "imageMenu.radius.smoother": "Łagodniejsze",
  "imageMenu.radius.rounded": "Zaokrąglone",
  "imageMenu.radius.circle": "Okrągłe",
  "imageMenu.lockAspectRatio": "Zablokuj proporcje",
  "imageMenu.lockAspectRatioLock": "Zablokuj proporcje",
  "imageMenu.lockAspectRatioUnlock": "Odblokuj proporcje",
  "imageMenu.sourceUrl": "Adres źródłowy",
  "imageMenu.externalUrl": "Zewnętrzny adres URL",
  "imageMenu.width": "Sz",
  "imageMenu.height": "Wy",
  "imageMenu.unitPx": "PX",
  "inlineImageMenu.sourceUrl": "Adres źródłowy",
  "inlineImageMenu.externalUrl": "Zewnętrzny adres URL",

  // ── Button menu ──
  "buttonMenu.borderRadius": "Zaokrąglenie rogów",
  "buttonMenu.radius.sharp": "Ostre",
  "buttonMenu.radius.smooth": "Lekkie",
  "buttonMenu.radius.round": "Zaokrąglone",
  "buttonMenu.style": "Styl",
  "buttonMenu.style.filled": "Wypełniony",
  "buttonMenu.style.outline": "Kontur",
  "buttonMenu.size": "Rozmiar",
  "buttonMenu.size.small": "Mały",
  "buttonMenu.size.medium": "Średni",
  "buttonMenu.size.large": "Duży",
  "buttonMenu.updateExternalLink": "Zmień zewnętrzny link",
  "buttonMenu.backgroundColor": "Kolor tła",
  "buttonMenu.textColor": "Kolor tekstu",

  // ── Column menu ──
  "columnMenu.gap": "Odstęp kolumn",
  "columnMenu.gap.none": "Brak",
  "columnMenu.delete": "Usuń kolumny",
  "columnMenu.width": "Sz",
  "columnMenu.fitContent": "Dopasuj do treści",
  "columnMenu.stretch": "Rozciągnij",
  "columnMenu.twoColumns": "2 kolumny",
  "columnMenu.threeColumns": "3 kolumny",
  "columnMenu.left": "Lewa",
  "columnMenu.right": "Prawa",
  "columnMenu.middle": "Środkowa",
  "columnMenu.autoPlaceholder": "auto",
  "columnMenu.unitPercent": "%",
  "columnMenu.configureWidths": "Ustaw szerokości kolumn",

  // ── Repeat menu ──
  "repeatMenu.label": "Powtórzenie",
  "repeatMenu.iterableHint":
    "Upewnij się, że wybrana zmienna jest iterowalna, np. tablica obiektów.",
  "repeatMenu.placeholder": "np. payload.items",
  "repeatMenu.selectBlock": "Wybierz blok powtórzenia",

  // ── HTML menu ──
  "htmlMenu.htmlCode": "Kod HTML",
  "htmlMenu.preview": "Podgląd",

  // ── Content (drag-handle) menu ──
  "contentMenu.addNode": "Dodaj nowy węzeł",
  "contentMenu.nodeActions": "Akcje węzła",
  "contentMenu.duplicate": "Duplikuj",
  "contentMenu.delete": "Usuń",

  // ── Show-conditionally popover ──
  "showPopover.showConditionally": "Pokaż blok warunkowo",
  "showPopover.showIf": "Pokaż jeśli",
  "showPopover.showIfHint": "Pokaż blok, jeśli wybrana zmienna jest prawdziwa.",

  // ── Link card ──
  "linkCard.imageAlt": "Obraz karty linku",
  "linkCard.image": "Obraz",
  "linkCard.imagePlaceholder": "Dodaj obraz",
  "linkCard.title": "Tytuł",
  "linkCard.titlePlaceholder": "Dodaj tytuł",
  "linkCard.description": "Opis",
  "linkCard.descriptionPlaceholder": "Dodaj opis",
  "linkCard.linkTitle": "Tytuł linku",
  "linkCard.linkTitlePlaceholder": "Dodaj tytuł linku",
  "linkCard.link": "Link",
  "linkCard.linkPlaceholder": "Dodaj link",
  "linkCard.badgeText": "Tekst etykiety",
  "linkCard.badgeTextPlaceholder": "Dodaj tekst etykiety",
  "linkCard.subTitle": "Podtytuł",
  "linkCard.subTitlePlaceholder": "Dodaj podtytuł",

  // ── Image and logo node status ──
  "imageStatus.noImage": "Nie wybrano obrazu",
  "imageStatus.dropImage": "Kliknij lub upuść obraz tutaj",
  "imageStatus.loading": "Ładowanie obrazu...",
  "imageStatus.error": "Błąd ładowania obrazu",
  "imageStatus.variable": "Zmienna adresu URL obrazu",
  "logo.alt": "Logo",

  // ── Variables ──
  "variableMenu.variable": "Zmienna",
  "variableMenu.variablePlaceholder": "np. imię",
  "variableMenu.default": "Wartość domyślna",
  "variableMenu.defaultPlaceholder": "np. Jan Kowalski",
  "variableMenu.title": "Zmienne",
  "variableMenu.noResult": "Brak wyników",
  "variableMenu.navigate": "Nawiguj",

  // ── Edge-spacing micro-labels (Góra/Prawo/Dół/Lewo) ──
  "edgeSpacing.top": "G",
  "edgeSpacing.right": "P",
  "edgeSpacing.bottom": "D",
  "edgeSpacing.left": "L",

  // ── Spacing scale ──
  "spacing.xs": "Bardzo mały",
  "spacing.sm": "Mały",
  "spacing.md": "Średni",
  "spacing.lg": "Duży",
  "spacing.xl": "Bardzo duży",

  // ── Misc ──
  "colorPicker.recentlyUsed": "Ostatnio używane",
  "colorPicker.open": "Otwórz wybór koloru",
  "colorPicker.useColor": "Użyj koloru {color}",
  "inputAutocomplete.placeholder": "np. items",
}

export const polishMailboxLabels: MailyMailboxLabels = {
  "compose.new": "Nowa wiadomość",
  "compose.editDraft": "Edytuj szkic",
  "compose.discard": "Odrzuć",
  "compose.saveDraft": "Zapisz szkic",
  "compose.send": "Wyślij",
  "compose.saved": "Szkic zapisany.",
  "compose.sent": "Wiadomość wysłana.",
  "compose.discarded": "Szkic odrzucony.",
  "compose.wrote": "W dniu {date} {sender} napisał(a):",
  "compose.forwardedHeader": "Przekazana wiadomość",
  "compose.mode.plainText": "Zwykły tekst",
  "compose.mode.mailyEditor": "Edytor Maily",
  "folders.inbox": "Odebrane",
  "folders.sent": "Wysłane",
  "folders.drafts": "Szkice",
  "folders.bounced": "Odbite",
  "actions.reply": "Odpowiedz",
  "actions.forward": "Przekaż",
  "actions.more": "Więcej",
  "actions.favorite": "Dodaj gwiazdkę",
  "actions.unfavorite": "Usuń gwiazdkę",
  "actions.react": "Dodaj reakcję",
  "actions.archive": "Archiwizuj",
  "actions.reportSpam": "Zgłoś spam",
  "actions.delete": "Usuń",
  "actions.markUnread": "Oznacz jako nieprzeczytane",
  "actions.blockSender": "Zablokuj nadawcę",
  "actions.reportPhishing": "Zgłoś phishing",
  "actions.reportIllegal": "Zgłoś nielegalne treści",
  "actions.filterSimilar": "Filtruj podobne wiadomości",
  "actions.translate": "Przetłumacz",
  "actions.print": "Drukuj",
  "actions.download": "Pobierz wiadomość",
  "actions.showOriginal": "Pokaż oryginał",
  "actions.feedback": "Przekaż opinię",
  "actions.openExternal": "Otwórz w nowym oknie",
  searchPlaceholder: "Szukaj poczty",
  refresh: "Odśwież",
  loading: "Ładowanie",
  "empty.noSelection": "Wybierz wiadomość",
  "empty.noSelectionDesc": "Wybierz wiadomość albo rozpocznij nowy szkic.",
  "empty.inbox": "Brak wiadomości odebranych.",
  "empty.sent": "Brak wysłanych wiadomości.",
  "empty.drafts": "Brak szkiców.",
  "empty.bounced": "Brak odbitych wiadomości.",
  "message.unknownSender": "Nieznany nadawca",
  "message.noSubject": "(brak tematu)",
  "message.noBody": "Brak treści wiadomości.",
  "message.toPrefix": "do",
  "message.cc": "DW",
  "message.bcc": "UDW",
  "message.to": "Do",
  "contacts.recipientPlaceholder": "name@example.com, other@example.com",
  "contacts.noSuggestions": "Nie znaleziono kontaktów.",
  "message.subject": "Temat",
  "message.body": "Treść",
  "message.bounced": "Odbita",
  "message.queued": "W kolejce",
  "message.attachments": "Załączniki ({count})",
  "errors.refresh": "Nie udało się odświeżyć poczty.",
  "errors.detail": "Nie udało się wczytać wiadomości.",
  "errors.saveDraft": "Nie udało się zapisać szkicu.",
  "errors.send": "Nie udało się wysłać wiadomości.",
  "errors.discard": "Nie udało się odrzucić szkicu.",
  "errors.messageAction": "Nie udało się zaktualizować wiadomości.",
}
